---
- name: Install epel-release
  yum:
    name: epel-release
    state: present

- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Start apache
  service:
    name: httpd
    state: started
    enabled: yes
